runtime: python37
entrypoint: gunicorn -b :8080 main:app
instance_class: F4
#[START gae_flex_storage_yaml]
#env_variables:
#    CLOUD_STORAGE_BUCKET: twocircle_generator
#[END gae_flex_storage_yaml]
handlers:

- url: /static'
  static_dir: static

- url: /.*
  script: auto
