runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

skip_files:
  - "backend/two_circles_generator.pt"

#[START gae_flex_storage_yaml]
env_variables:
    CLOUD_STORAGE_BUCKET: twocircle_generator
#[END gae_flex_storage_yaml]
